#+TITLE: Pop yeast gene info in Emacs

* What is ~sgd-lookup.el~?

An Emacs API wrapper for [[https://www.yeastgenome.org][Saccharomyces Genome Database (SGD)]].

It allows quick access to gene info when I read or write in Emacs.

Note: This is NOT part of SGD.

* Installation

1. Clone or download this repository (path of folder is ~<path-to-sgd-lookup>~ below).

2. In your ~.emacs~ file (or ~.doom.d/config.el~ if you are using Doom Emacs), add the following lines:
   #+begin_src elisp
(add-to-list 'load-path "<path-to-sgd-lookup>")
(require 'sgd-lookup)
   #+end_src

* Usage

Type a gene name (e.g. GAL2) and move cursor onto it in an arbitrary buffer, and then:

+ ~M-x sgd-lookup-description~ pops up a window at the bottom to show the name description and description of that gene.
+ ~M-x sgd-lookup-paragraph~ pops up a window at the bottom to show the detailed description of that gene.
+ ~M-x sgd-lookup-gene-homepage~ opens the SGD page of that gene with default browser.
+ ~M-x sgd-lookup-gene-info~ asks the user to choose a category of info (e.g. homolog) and then a database (e.g. FungiDB) and opens the corresponding webpage of that gene with default browser.
