#+TITLE: Pop yeast gene info in Emacs

** What is ~sgd-lookup.el~?

An Emacs API wrapper for [[https://www.yeastgenome.org][Saccharomyces Genome Database (SGD)]].

It allows quick access to gene info when I read or write in Emacs.

Note: This is NOT part of SGD.

** Installation

1. Clone or download this repository (path of folder is ~<path-to-sgd-lookup>~ below).

2. In your ~.emacs~ file (or ~.doom.d/config.el~ if you are using Doom Emacs), add the following lines:
   #+begin_src elisp
(add-to-list 'load-path "<path-to-sgd-lookup>")
(require 'sgd-lookup)
   #+end_src

** Usage

+ ~M-x sgd-lookup~ prompts for a gene name (e.g. GAL2 or YLR081W) and then action.
+ ~M-x sgd-lookup-at-point~ reads the gene name at the cursor and prompts for action.

Available actions:
+ ~description~: show description of a gene in a pop-up window.
+ ~summary paragraph~: show summary paragraph of a gene in a pop-up window (if exists).
+ ~phenotype~: show phenotype overview of a gene in a pop-up window (if exists).
+ ~visit in browser~: visit gene entry in default browser.
+ ~more URLs~: prompts for a category of info (e.g. homolog) and then a database (e.g. FungiDB).
  Open URLs provided by SGD to internal and external databases.

Feedback and feature requests are welcomed!

** Release history
+ Version ~0.1.1~: Supports new action: ~phenotype~.
+ Version ~0.1.0~: ~sgd-lookup-description~, ~sgd-lookup-paragraph~, ~sgd-lookup-gene-homepage~ and ~sgd-lookup-gene-info~ are no longer interactive.
  To achieve the same behaviour, use ~sgd-lookup-at-point~ instead.
+ Version ~0.0.4~: original release.
